pipeline {
    agent {
        label "jenkins-agent"
    }
    options {
        ansiColor('xterm')
    }
    parameters {
        string(name: 'pacBrokerServerIP', defaultValue: 'localhost', description: "PACT BROKER IP")

    }
    stages {
        stage('Build') {
            steps {
                sh './gradlew assemble'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Publish') {
            steps {
                sh "./gradlew -PpacBrokerServerIP=${params.pacBrokerServerIP} pactPublish"
            }
        }
    }
}
